### ISSUE TITLE
User can inject html and scripts in add user form

### ISSUE THREAD

**Issue by NolanFoster** [StratusPrint/WebControlPanel#27]
![htmlinjection](https://cloud.githubusercontent.com/assets/4382789/15022785/4b7a776e-11fb-11e6-97d4-bfb924c5be4e.png)

**Comment by NolanFoster** [comment]
I added <b>test</b> it shouldn't be bold

**Comment by Mikodin** [comment]
This probably applies to all forms.  Interesting I will look into fixing this! No bueno
