### ISSUE TITLE
Possibly broke User Management page

### ISSUE THREAD

**Issue by mlbogdan** [StratusPrint/WebControlPanel#34]
When editing a user name in User Management (admin) - Edited my username to "Admin", clicked save changes, and "Users" list is stuck in "loading".  Closing and reopening/loading page did not work.  Had to sign out, then sign back in to get list to populate and have the name change take place. 
![image](https://cloud.githubusercontent.com/assets/9124591/15092687/624c1e02-143f-11e6-94d0-0884868c461e.png)

**Comment by bobmshannon** [comment]
This seems to happen if a user revokes admin privileges from their own account -- in which case they are not allowed to fetch any user data -- but the frontend doesn't seem to convey that information and instead stays stuck in a loading state.

We'll need to figure out a way to handle this more gracefully.

**Comment by Mikodin** [comment]
Quick fix, to make it so an admin cannot remove their own access?  Or it forces them to logout
